/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Santana Mares Jasmin Aide sant.mar.1997@gmail.com
 */
public class ViewReport extends javax.swing.JFrame {

    /**
     * Creates new form ViewReport
     */
    public ViewReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPrin = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panBoton = new javax.swing.JPanel();
        bntGenerar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        psnContenido = new javax.swing.JPanel();
        panSelect = new javax.swing.JPanel();
        chkNum = new javax.swing.JCheckBox();
        chkNombre = new javax.swing.JCheckBox();
        chkContenido = new javax.swing.JCheckBox();
        panOrdenar = new javax.swing.JPanel();
        cboNumero = new javax.swing.JComboBox();
        cboNombre = new javax.swing.JComboBox();
        cboContenido = new javax.swing.JComboBox();
        panTipo = new javax.swing.JPanel();
        rdbAsc = new javax.swing.JRadioButton();
        rdbDes = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panPrin.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Reporte de Articulos");

        javax.swing.GroupLayout panTituloLayout = new javax.swing.GroupLayout(panTitulo);
        panTitulo.setLayout(panTituloLayout);
        panTituloLayout.setHorizontalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        panTituloLayout.setVerticalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        panPrin.add(panTitulo, java.awt.BorderLayout.PAGE_START);

        bntGenerar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        bntGenerar.setForeground(new java.awt.Color(153, 0, 0));
        bntGenerar.setText("Generar");
        bntGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGenerarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(153, 0, 0));
        btnSalir.setText("Salir");

        javax.swing.GroupLayout panBotonLayout = new javax.swing.GroupLayout(panBoton);
        panBoton.setLayout(panBotonLayout);
        panBotonLayout.setHorizontalGroup(
            panBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotonLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(bntGenerar)
                .addGap(48, 48, 48)
                .addComponent(btnSalir)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        panBotonLayout.setVerticalGroup(
            panBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotonLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(panBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntGenerar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        panPrin.add(panBoton, java.awt.BorderLayout.PAGE_END);

        psnContenido.setLayout(new java.awt.GridLayout(1, 3));

        panSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panSelect.setName("Selecciona Los campos"); // NOI18N

        chkNum.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        chkNum.setForeground(new java.awt.Color(0, 0, 255));
        chkNum.setText("Numero de articulo");

        chkNombre.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        chkNombre.setForeground(new java.awt.Color(0, 0, 255));
        chkNombre.setText("Nombre");

        chkContenido.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        chkContenido.setForeground(new java.awt.Color(0, 0, 255));
        chkContenido.setText("Contenido");

        javax.swing.GroupLayout panSelectLayout = new javax.swing.GroupLayout(panSelect);
        panSelect.setLayout(panSelectLayout);
        panSelectLayout.setHorizontalGroup(
            panSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkNum, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(chkNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panSelectLayout.setVerticalGroup(
            panSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkNombre)
                .addGap(3, 3, 3)
                .addComponent(chkContenido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        psnContenido.add(panSelect);

        panOrdenar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panOrdenar.setName("Ordenancion de campos"); // NOI18N

        cboNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboNombre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboContenido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panOrdenarLayout = new javax.swing.GroupLayout(panOrdenar);
        panOrdenar.setLayout(panOrdenarLayout);
        panOrdenarLayout.setHorizontalGroup(
            panOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panOrdenarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboContenido, 0, 149, Short.MAX_VALUE)
                    .addComponent(cboNombre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboNumero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panOrdenarLayout.setVerticalGroup(
            panOrdenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOrdenarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        psnContenido.add(panOrdenar);

        panTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panTipo.setName("Tipo de orden"); // NOI18N

        rdbAsc.setText("Ascendente");

        rdbDes.setText("Descendente");

        javax.swing.GroupLayout panTipoLayout = new javax.swing.GroupLayout(panTipo);
        panTipo.setLayout(panTipoLayout);
        panTipoLayout.setHorizontalGroup(
            panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTipoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbDes)
                    .addComponent(rdbAsc))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panTipoLayout.setVerticalGroup(
            panTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTipoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rdbAsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbDes)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        psnContenido.add(panTipo);

        panPrin.add(psnContenido, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPrin, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGenerarActionPerformed
        // TODO add your handling code here:
        new Reporte();
       
    }//GEN-LAST:event_bntGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGenerar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboContenido;
    private javax.swing.JComboBox cboNombre;
    private javax.swing.JComboBox cboNumero;
    private javax.swing.JCheckBox chkContenido;
    private javax.swing.JCheckBox chkNombre;
    private javax.swing.JCheckBox chkNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panBoton;
    private javax.swing.JPanel panOrdenar;
    private javax.swing.JPanel panPrin;
    private javax.swing.JPanel panSelect;
    private javax.swing.JPanel panTipo;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JPanel psnContenido;
    private javax.swing.JRadioButton rdbAsc;
    private javax.swing.JRadioButton rdbDes;
    // End of variables declaration//GEN-END:variables
}
