/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Santana Mares Jasmin Aide sant.mar.1997@gmail.com
 */
public class Calculadora extends javax.swing.JFrame {

    private double total; //Almacena el total
    private char operacion; //recuerda la operacion que se va a ejecutar

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        //Objeto chismos
        ActionListener eventoClic = new EventoClic();

        /* Vamos iterando por todos los componentes del JFrame
         * y el que sea una instancia de la clase JButton le establecemos
         * el chismoso
         */
        for (Component comp : panBotones.getComponents()) {
            if (comp instanceof JButton) {
                ((JButton) comp).addActionListener(eventoClic);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisplay = new javax.swing.JLabel();
        btnEqual = new javax.swing.JButton();
        panBotones = new javax.swing.JPanel();
        btnAc = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        bntPunto = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        bntOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcuadora");
        setMinimumSize(new java.awt.Dimension(280, 200));
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        lblDisplay.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lblDisplay.setForeground(new java.awt.Color(0, 51, 255));
        lblDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisplay.setText(" ");
        getContentPane().add(lblDisplay, java.awt.BorderLayout.PAGE_START);

        btnEqual.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(btnEqual, java.awt.BorderLayout.PAGE_END);

        panBotones.setLayout(new java.awt.GridLayout(4, 4, 5, 5));

        btnAc.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnAc.setForeground(new java.awt.Color(204, 0, 204));
        btnAc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/X.png"))); // NOI18N
        btnAc.setText("AC");
        btnAc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcMouseExited(evt);
            }
        });
        btnAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcActionPerformed(evt);
            }
        });
        panBotones.add(btnAc);

        btnCero.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnCero.setForeground(new java.awt.Color(204, 0, 204));
        btnCero.setText("0");
        btnCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCeroMouseClicked(evt);
            }
        });
        panBotones.add(btnCero);

        bntPunto.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        bntPunto.setForeground(new java.awt.Color(204, 0, 204));
        bntPunto.setText(".");
        bntPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPuntoActionPerformed(evt);
            }
        });
        panBotones.add(bntPunto);

        btnSuma.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnSuma.setForeground(new java.awt.Color(204, 0, 204));
        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Plus.png"))); // NOI18N
        btnSuma.setText("+");
        panBotones.add(btnSuma);

        btnSiete.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnSiete.setForeground(new java.awt.Color(204, 0, 204));
        btnSiete.setText("7");
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });
        panBotones.add(btnSiete);

        bntOcho.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        bntOcho.setForeground(new java.awt.Color(204, 0, 204));
        bntOcho.setText("8");
        bntOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOchoActionPerformed(evt);
            }
        });
        panBotones.add(bntOcho);

        btnNueve.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnNueve.setForeground(new java.awt.Color(204, 0, 204));
        btnNueve.setText("9");
        panBotones.add(btnNueve);

        btnResta.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnResta.setForeground(new java.awt.Color(204, 0, 204));
        btnResta.setText("-");
        panBotones.add(btnResta);

        btnCuatro.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnCuatro.setForeground(new java.awt.Color(204, 0, 204));
        btnCuatro.setText("4");
        panBotones.add(btnCuatro);

        btnCinco.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnCinco.setForeground(new java.awt.Color(204, 0, 204));
        btnCinco.setText("5");
        panBotones.add(btnCinco);

        btnSeis.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnSeis.setForeground(new java.awt.Color(204, 0, 204));
        btnSeis.setText("6");
        panBotones.add(btnSeis);

        btnMultiplicar.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(204, 0, 204));
        btnMultiplicar.setText("*");
        panBotones.add(btnMultiplicar);

        btnUno.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnUno.setForeground(new java.awt.Color(204, 0, 204));
        btnUno.setText("1");
        panBotones.add(btnUno);

        btnDos.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnDos.setForeground(new java.awt.Color(204, 0, 204));
        btnDos.setText("2");
        panBotones.add(btnDos);

        btnTres.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnTres.setForeground(new java.awt.Color(204, 0, 204));
        btnTres.setText("3");
        panBotones.add(btnTres);

        btnDividir.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(204, 0, 204));
        btnDividir.setText("/");
        panBotones.add(btnDividir);

        getContentPane().add(panBotones, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        // TODO add your handling code here:
        //lblDisplay.setText(lblDisplay.getText()+"");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
        // TODO add your handling code here:
        lblDisplay.setText(" ");
        total = 0.0;
        operacion = ' ';
    }//GEN-LAST:event_btnAcActionPerformed

    private void bntOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOchoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bntOchoActionPerformed

    private void bntPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPuntoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bntPuntoActionPerformed

    private void btnAcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcMouseEntered
        // TODO add your handling code here:
        btnAc.setSize(120, 100);
    }//GEN-LAST:event_btnAcMouseEntered

    private void btnAcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcMouseExited
        // TODO add your handling code here:
        btnAc.setSize(110, 60);
    }//GEN-LAST:event_btnAcMouseExited

    private void btnCeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCeroMouseClicked
        // TODO add your handling code here:
        btnCero.setForeground(Color.blue);
        btnCero.setBackground(Color.cyan);
    }//GEN-LAST:event_btnCeroMouseClicked

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
        if (operacion == '+') //realizar el calculo en base a operaciÃ³n
        {
            total = total + Double.valueOf(lblDisplay.getText());
        }
        
        if (operacion == '-') //realizar el calculo en base a operaciÃ³n
                {
            total = total- Double.valueOf(lblDisplay.getText());
        }
        if (operacion == '*') //realizar el calculo en base a operaciÃ³n
                {
            total = total * Double.valueOf(lblDisplay.getText());
        }
         if (operacion == '/') //realizar el calculo en base a operaciÃ³n
                {
            total = total / Double.valueOf(lblDisplay.getText());
        }
        lblDisplay.setText("" + total);
        total = 0;
        operacion = ' ';

    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    class EventoClic implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            //Saber que botÃ³n se le hizo clic
            String texto = ((JButton) e.getSource()).getText();

            //Decidir de que botÃ³n proviene el clic en base a su tÃ­tulo
            switch (texto) {
                case "0":
                case "1":
                case "2":
                case "3":
                case "4":
                case "5":
                case "6":
                case "7":
                case "8":
                case "9":
                    //Checar cuando inicie con 0.0
                    lblDisplay.setText(lblDisplay.getText() + texto);
                    break;
                case "+":
                    operacion = '+';//OperaciÃ³n a realizar
                    total = total + Double.valueOf(lblDisplay.getText().trim());
                    lblDisplay.setText("");//Inicializa display
                    break;
                case "-":
                    operacion = '-';
                    total =   Double.valueOf(lblDisplay.getText().trim());
                    lblDisplay.setText("");//Inicializa display
                    break;
                case "*":
                    operacion = '*';
                    total =  Double.valueOf(lblDisplay.getText().trim()) ;
                    lblDisplay.setText("");//Inicializa display
                    break;
                case "/":
                    operacion = '/';
                    total = Double.valueOf(lblDisplay.getText().trim());
                    lblDisplay.setText("");//Inicializa display
                    break;
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntOcho;
    private javax.swing.JButton bntPunto;
    private javax.swing.JButton btnAc;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JPanel panBotones;
    // End of variables declaration//GEN-END:variables
}
