/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AccessMySQL;
import dao.EntradaMateria;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MateriaEntrada;


/**
 *
 * @author tyrrang
 */
public class viewSalidaMateriaPrima extends javax.swing.JFrame {
String mensaje="";
    /**
     * Creates new form viewSalidaMateriaPrima
     */

         private EntradaMateria dao=new EntradaMateria();
         
    public viewSalidaMateriaPrima() {
        initComponents();
        DefaultComboBoxModel modeloCant = new DefaultComboBoxModel();
             modeloCant.addElement("Cantidad");
        List<MateriaEntrada> lista = dao.getListaMateria();
        
                cboMateriaPrima.removeAllItems();
         for (MateriaEntrada materia : lista) {
            cboMateriaPrima.addItem(materia.getNombreMP());
        }
        
         for (int i = 1; i < 50; i++) {
            modeloCant.addElement(i);

        }    
          cboCantidad.setModel(modeloCant);
                   
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlBarra = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnSalida1 = new javax.swing.JButton();
        btnCerrarS = new javax.swing.JButton();
        pnlSalidaMateriaPrima = new javax.swing.JPanel();
        lblMateriaPrima = new javax.swing.JLabel();
        cboMateriaPrima = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        cboCantidad = new javax.swing.JComboBox<>();
        btnSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogo.setBackground(new java.awt.Color(122, 35, 35));

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 194, 141));
        jLabel1.setText("Damayte Dulce Gourmet");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 194, 141));
        jLabel3.setText("Salida de Materia Prima");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logodesktop.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1))
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogo, java.awt.BorderLayout.PAGE_START);

        pnlBarra.setBackground(new java.awt.Color(9, 57, 5));
        pnlBarra.setPreferredSize(new java.awt.Dimension(449, 35));

        btnRegistro.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        pnlBarra.add(btnRegistro);

        btnEntrada.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnEntrada.setText("Entradas");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        pnlBarra.add(btnEntrada);

        btnSalida1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnSalida1.setText("Salidas");
        btnSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalida1ActionPerformed(evt);
            }
        });
        pnlBarra.add(btnSalida1);

        btnCerrarS.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnCerrarS.setText("Cerrar Sesion");
        btnCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSActionPerformed(evt);
            }
        });
        pnlBarra.add(btnCerrarS);

        getContentPane().add(pnlBarra, java.awt.BorderLayout.CENTER);

        pnlSalidaMateriaPrima.setBackground(new java.awt.Color(213, 194, 141));

        lblMateriaPrima.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblMateriaPrima.setText("Nombre Materia Prima");

        cboMateriaPrima.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        cboMateriaPrima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Item 2", "Item 3", "Item 4" }));

        lblCantidad.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad");

        cboCantidad.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        cboCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cantidad", "Item 2", "Item 3", "Item 4" }));

        btnSalida.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnSalida.setText("Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalidaMateriaPrimaLayout = new javax.swing.GroupLayout(pnlSalidaMateriaPrima);
        pnlSalidaMateriaPrima.setLayout(pnlSalidaMateriaPrimaLayout);
        pnlSalidaMateriaPrimaLayout.setHorizontalGroup(
            pnlSalidaMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalidaMateriaPrimaLayout.createSequentialGroup()
                .addGroup(pnlSalidaMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSalidaMateriaPrimaLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSalida)
                        .addGap(0, 243, Short.MAX_VALUE))
                    .addGroup(pnlSalidaMateriaPrimaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSalidaMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSalidaMateriaPrimaLayout.createSequentialGroup()
                                .addComponent(lblCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSalidaMateriaPrimaLayout.createSequentialGroup()
                                .addComponent(lblMateriaPrima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlSalidaMateriaPrimaLayout.setVerticalGroup(
            pnlSalidaMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalidaMateriaPrimaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlSalidaMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMateriaPrima))
                .addGap(34, 34, 34)
                .addGroup(pnlSalidaMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(cboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalida)
                .addGap(22, 22, 22))
        );

        getContentPane().add(pnlSalidaMateriaPrima, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        viewRegistroMateriaPrima registro = new viewRegistroMateriaPrima();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        viewEntradaMateriaPrima entrada = new viewEntradaMateriaPrima();
        entrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalida1ActionPerformed
        viewSalidaMateriaPrima salida = new viewSalidaMateriaPrima();
        salida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalida1ActionPerformed

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
        JOptionPane.showMessageDialog(null, "Hasta Pronto");
        viewLogin login = new viewLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
       
    try {
        AccessMySQL objCon = AccessMySQL.getInstance();
        //Paso 1 obtener la conexion
        Connection con=objCon.getConnection();
        String nom,cant;
        nom=cboMateriaPrima.getSelectedItem().toString();
        cant=cboCantidad.getSelectedItem().toString();
        
        Statement stmt= con.createStatement();
        String query= "SELECT cantidad "
                + "FROM materiaprima where nombreMP='"+nom+ "' ";
       
        ResultSet rsut = stmt.executeQuery(query);
        if(rsut.next()){
           
            String update="UPDATE materiaprima SET  cantidad=cantidad -'"+cant+"' WHERE nombreMP='"+nom+"' ";
            stmt.executeUpdate(update);
        }
        if(cboMateriaPrima.getSelectedItem().equals("Nombre")){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la Materia Prima","Mensaje",JOptionPane.ERROR_MESSAGE);
            
        } else if(cboCantidad.getSelectedItem().equals("Cantidad")){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la cantidad","Mensaje",JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        Logger.getLogger(viewSalidaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
    }//GEN-LAST:event_btnSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSalidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSalidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSalidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSalidaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSalidaMateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalida;
    private javax.swing.JButton btnSalida1;
    private javax.swing.JComboBox<String> cboCantidad;
    private javax.swing.JComboBox<String> cboMateriaPrima;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlSalidaMateriaPrima;
    // End of variables declaration//GEN-END:variables
}
