/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AccessMySQL;
import dao.EntradaMateria;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MateriaEntrada;

/**
 *
 * @author Santana Mares Jasmin Aide sant.mar.1997@gmail.com
 */
public class viewRegistroMateriaPrima extends javax.swing.JFrame {
    String mensaje="";
      private EntradaMateria dao=new EntradaMateria();
    /**
     * Creates new form viewRegistroMateriaPrima
     */
    public viewRegistroMateriaPrima() {
        initComponents();
         
        DefaultComboBoxModel modeloCant = new DefaultComboBoxModel();
          
        List<MateriaEntrada> lista = dao.getListaMateria();
        
                cboProduct.removeAllItems();
         
                for (MateriaEntrada materia : lista) {
            cboProduct.addItem(materia.getNombreMP());
        }
        
         
         
        
         
      initCombos();
    }


    /*
    * Inicializa los combos
     */
    private void initCombos() {
        DefaultComboBoxModel modeloDia = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloAnio = new DefaultComboBoxModel();
       
        modeloDia.addElement("Dia");
        modeloAnio.addElement("Año");

        for (int i = 1; i < 31; i++) {
            modeloDia.addElement(i);

        }
      

        for (int a = 2050; a >= 2016; a--) {
            modeloAnio.addElement(a);

        }
        
        cboDiaF.setModel(modeloDia);
        cboAñoF.setModel(modeloAnio);
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlRegistroMateria = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tblRegistroMateria = new javax.swing.JTabbedPane();
        pnlRegistroDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblFecha = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        cboUnidadMedida = new javax.swing.JComboBox<String>();
        cboDiaF = new javax.swing.JComboBox<String>();
        cboMesF = new javax.swing.JComboBox<String>();
        cboAñoF = new javax.swing.JComboBox<String>();
        btnRegistrar = new javax.swing.JButton();
        txtReorden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaMateria = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtExistente = new javax.swing.JTextField();
        cboProduct = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        txtNuevo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlBarra = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnCerrarS = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(525, 700));
        setPreferredSize(new java.awt.Dimension(200, 300));

        pnlLogo.setBackground(new java.awt.Color(122, 35, 35));

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 194, 141));
        jLabel1.setText("Damayte Dulce Gourmet");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 194, 141));
        jLabel3.setText("Registro de Materia");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logodesktop.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel3)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogo, java.awt.BorderLayout.PAGE_START);

        pnlRegistroMateria.setBackground(new java.awt.Color(213, 194, 141));

        jPanel3.setBackground(new java.awt.Color(213, 194, 141));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));
        jPanel3.setForeground(new java.awt.Color(51, 0, 51));

        tblRegistroMateria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblRegistroMateria.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        tblRegistroMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegistroMateriaMouseClicked(evt);
            }
        });

        pnlRegistroDatos.setBackground(new java.awt.Color(213, 194, 141));
        pnlRegistroDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Producto"));

        lblNombre.setBackground(new java.awt.Color(204, 255, 204));
        lblNombre.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");

        lblDescripcion.setBackground(new java.awt.Color(204, 255, 204));
        lblDescripcion.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("Descripción");

        lblCantidad.setBackground(new java.awt.Color(204, 255, 204));
        lblCantidad.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        lblFecha.setBackground(new java.awt.Color(204, 255, 204));
        lblFecha.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha de Caducidad");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        cboUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UNIDADES DE MEDIDA", "Unidad", "Litro", "Mililitro", "Kilogramo", "Gramo" }));

        cboDiaF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDiaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDiaFActionPerformed(evt);
            }
        });

        cboMesF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        cboMesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMesFActionPerformed(evt);
            }
        });

        cboAñoF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Nivel Reorden");

        javax.swing.GroupLayout pnlRegistroDatosLayout = new javax.swing.GroupLayout(pnlRegistroDatos);
        pnlRegistroDatos.setLayout(pnlRegistroDatosLayout);
        pnlRegistroDatosLayout.setHorizontalGroup(
            pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addGap(18, 18, 18))
                            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)))
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboDiaF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReorden))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                                .addComponent(cboMesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboAñoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRegistrar))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        pnlRegistroDatosLayout.setVerticalGroup(
            pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistroDatosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDiaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAñoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegistrar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        tblRegistroMateria.addTab("Datos del Producto", pnlRegistroDatos);

        pnlLista.setBackground(new java.awt.Color(213, 194, 141));
        pnlLista.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));
        pnlLista.setForeground(new java.awt.Color(255, 204, 51));
        pnlLista.setLayout(new java.awt.CardLayout());

        tblListaMateria.setBackground(new java.awt.Color(213, 194, 141));
        tblListaMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Cantidad", "Fecha ", "Fecha Caducidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaMateria);

        pnlLista.add(jScrollPane1, "card2");

        tblRegistroMateria.addTab("Listado de Productos", pnlLista);

        jPanel1.setBackground(new java.awt.Color(213, 194, 141));

        cboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProductActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Productos:");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel5.setText("Nivel d eorden existente:");

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel6.setText("Nuevo nivel de reorden:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboProduct, javax.swing.GroupLayout.Alignment.TRAILING, 0, 164, Short.MAX_VALUE)
                    .addComponent(txtExistente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jLabel6))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        tblRegistroMateria.addTab("Nivel de Reorden", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tblRegistroMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblRegistroMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblRegistroMateria.getAccessibleContext().setAccessibleName("Datos de Materia Prima");

        javax.swing.GroupLayout pnlRegistroMateriaLayout = new javax.swing.GroupLayout(pnlRegistroMateria);
        pnlRegistroMateria.setLayout(pnlRegistroMateriaLayout);
        pnlRegistroMateriaLayout.setHorizontalGroup(
            pnlRegistroMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegistroMateriaLayout.setVerticalGroup(
            pnlRegistroMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlRegistroMateria, java.awt.BorderLayout.PAGE_END);

        pnlBarra.setBackground(new java.awt.Color(9, 57, 5));
        pnlBarra.setPreferredSize(new java.awt.Dimension(449, 35));

        btnRegistro.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        pnlBarra.add(btnRegistro);

        btnEntrada.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnEntrada.setText("Entradas");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });
        pnlBarra.add(btnEntrada);

        btnSalida.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnSalida.setText("Salidas");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        pnlBarra.add(btnSalida);

        btnCerrarS.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnCerrarS.setText("Cerrar Sesion");
        btnCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSActionPerformed(evt);
            }
        });
        pnlBarra.add(btnCerrarS);

        jButton3.setText("Imprimir");
        pnlBarra.add(jButton3);

        getContentPane().add(pnlBarra, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboMesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMesFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMesFActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            //Paso 2 Crear un enunciado
           Date now = new Date(System.currentTimeMillis());
        Calendar cal1 = Calendar.getInstance();
        cal1.setTime(now);
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");// Indica el formato de la fecha 

        
        try {
            AccessMySQL objCon = AccessMySQL.getInstance();
            //Paso 1 obtener la conexion
            Connection con=objCon.getConnection();
        
            Statement stmt=con.createStatement();

String fechaCaducidad = cboAñoF.getSelectedItem() + "-"
                    + 
                    cboMesF.getSelectedItem() + "-"
                    + cboDiaF.getSelectedItem();

String in = "INSERT INTO `materiaprima` "
                        + "( `nombreMP`, `cantidad`, `descripcion`, `fechaAlta`, `fechaCaducidad`, `unidadMedidad`,`NivelReorden`) "
                        + "VALUES ('" + txtNombre.getText() + "', '" + txtCantidad.getText() + "', '" + txtDescripcion.getText()
                        + "', '" + date.format(now) + "', '" + fechaCaducidad + "', '" + cboUnidadMedida.getSelectedItem() + "'," + txtReorden.getText() + ")";

                stmt.executeUpdate(in);
                JOptionPane.showMessageDialog(null, "Inserccion Exitosa  ");
            
            //////////////////////parallenar la tabla
            String fechaa = cboDiaF.getSelectedItem() + "/"
                    + cboMesF.getSelectedItem() + "/"
                    + cboAñoF.getSelectedItem();
            Object[] rowData = new Object[]{
                txtDescripcion.getText(), txtNombre.getText(), txtCantidad.getText(),
                cboUnidadMedida.getSelectedItem(),
               // fecha
            };  DefaultTableModel modelo = (DefaultTableModel) tblListaMateria.getModel();
            if (validarCajas()) {
                modelo.addRow(rowData);
                JOptionPane.showMessageDialog(null, "Se Registro Correctamente",
                        "Alta de Producto", JOptionPane.INFORMATION_MESSAGE);
            } else {
                
                JOptionPane.showMessageDialog(null, mensaje,
                        "o Seleccionar la informacion",
                        JOptionPane.ERROR_MESSAGE);

        }
        } catch (SQLException ex) {
            Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private boolean validarCajas() {
        boolean isValido = true;
        mensaje = "";
        
        
        if (txtNombre.getText().trim().isEmpty()) {
            mensaje = mensaje + "El nombre  está vacío\n";
            isValido = false;
        }else
        if (txtDescripcion.getText().trim().isEmpty()) {
            mensaje = mensaje + "La Descripcion  está vacía\n";
            isValido = false;
        }else
        if (txtCantidad.getText().trim().isEmpty()) {
            mensaje = mensaje + "La Cantidad está vacía\n";
            isValido = false;
        }else
        if (cboUnidadMedida.getSelectedItem().equals("UNIDADES DE MEDIDA")) {
            mensaje = mensaje + "La Unidad de Medida esta vacia\n";
            isValido = false;
        }else
        if (cboDiaF.getSelectedItem().equals("Dia")) {
            mensaje = mensaje + "El dia esta vacío\n";
            isValido = false;
        }else
        if (cboMesF.getSelectedItem().toString().trim().equals("Mes")) {
            mensaje = mensaje + "El mes esta vacio\n";
            isValido = false;
        }else
        if(cboAñoF.getSelectedItem().equals("Año")) {
            mensaje = mensaje + "El año esta vacio\n";
            isValido = false;
        }
        return isValido;
    }
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        viewRegistroMateriaPrima registro = new viewRegistroMateriaPrima();
            registro.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        viewEntradaMateriaPrima entrada = new viewEntradaMateriaPrima();
        entrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        viewSalidaMateriaPrima salida = new viewSalidaMateriaPrima();
        salida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
        JOptionPane.showMessageDialog(null, "Hasta Pronto");
        viewLogin login = new viewLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char car=evt.getKeyChar();
        if(txtNombre.getText().length()>=50)
            evt.consume();
        if(!Character.isLetter(car)){
            if(!Character.isSpaceChar(car)){
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
        char car=evt.getKeyChar();
        if(!Character.isDigit(car)){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void cboDiaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDiaFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboDiaFActionPerformed

    private void tblRegistroMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegistroMateriaMouseClicked
        
        
        
        
    }//GEN-LAST:event_tblRegistroMateriaMouseClicked

    private void cboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductActionPerformed
        try {
            // TODO add your handling code here:

            
            AccessMySQL objCon = AccessMySQL.getInstance();
            //Paso 1 obtener la conexion
            Connection con=objCon.getConnection();
        
            Statement stmt=con.createStatement();
            
           ResultSet rst=stmt.executeQuery("Select * FROM materiaprima where nombreMP= '"+  cboProduct.getSelectedItem()+ "' ");
            
            System.out.println(" "+rst);
            if(rst.next()){
                               
                 txtExistente.setText(rst.getString("NivelReorden"));
                   
             
            
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cboProductActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        try {
            AccessMySQL objCon = AccessMySQL.getInstance();
            //Paso 1 obtener la conexion
            Connection con=objCon.getConnection();
            String nom,cant;
            nom=cboProduct.getSelectedItem().toString();
            cant=txtNuevo.getText();
            Statement stmt= con.createStatement();
            String query= "SELECT NivelReorden "
                    + "FROM materiaprima where nombreMP='"+nom+ "' ";
            ResultSet rsut = stmt.executeQuery(query);
            if(rsut.next()){
                
                String update="UPDATE materiaprima SET  NivelReorden=NivelReorden +'"+cant+"' WHERE nombreMP='"+nom+"' ";
                stmt.executeUpdate(update);
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRegistroMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRegistroMateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalida;
    private javax.swing.JComboBox<String> cboAñoF;
    private javax.swing.JComboBox<String> cboDiaF;
    private javax.swing.JComboBox<String> cboMesF;
    private javax.swing.JComboBox cboProduct;
    private javax.swing.JComboBox<String> cboUnidadMedida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlLista;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlRegistroDatos;
    private javax.swing.JPanel pnlRegistroMateria;
    private javax.swing.JTable tblListaMateria;
    private javax.swing.JTabbedPane tblRegistroMateria;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtExistente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevo;
    private javax.swing.JTextField txtReorden;
    // End of variables declaration//GEN-END:variables

    
}
