/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AccessMySQL;
import dao.EntradaMateria;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.MateriaEntrada;

/**
 *
 * @author tyrrang
 */
public class viewEntradaMateriaPrima extends javax.swing.JFrame {
        private EntradaMateria dao=new EntradaMateria();
   //constructor
        public viewEntradaMateriaPrima() {
        initComponents();
          DefaultComboBoxModel modeloAnio = new DefaultComboBoxModel();
           DefaultComboBoxModel modeloDia = new DefaultComboBoxModel();
           DefaultComboBoxModel modeloCant = new DefaultComboBoxModel();
            
             modeloAnio.addElement("Año");
             modeloDia.addElement("Dia");
        List<MateriaEntrada> lista = dao.getListaMateria();
        
                cboMateriaPrima.removeAllItems();
         for (MateriaEntrada materia : lista) {
            cboMateriaPrima.addItem(materia.getNombreMP());
        }
        
           for (int i = 1; i < 50; i++) {
            modeloCant.addElement(i);

        }    
         
         for (int i = 1; i < 31; i++) {
            modeloDia.addElement(i);

        }
          for (int a = 2050; a >= 2016; a--) {
            modeloAnio.addElement(a);

        }
                   cboCantidad.setModel(modeloCant);
                 cboAnio.setModel(modeloAnio);
        cboDia.setModel(modeloDia);
        
        
       // initCombos();
    }

//    private void initCombos() {
//
//        DefaultComboBoxModel modeloDia = new DefaultComboBoxModel();
//        DefaultComboBoxModel modeloAnio = new DefaultComboBoxModel();
//        DefaultComboBoxModel matera = new DefaultComboBoxModel();
//        DefaultComboBoxModel cantidad = new DefaultComboBoxModel();
//
//        matera.addElement("Seleccione la Materia prima");
//       // matera.addElement("Harina");
//        cantidad.addElement("Sleccione la cantidad");
//        cantidad.addElement("456");
//        modeloDia.addElement("Dia");
//        modeloAnio.addElement("Año");
//
//        for (int i = 1; i < 32; i++) {
//            modeloDia.addElement(i);
//        }
//        for (int a = 2016; a >= 1920; a--) {
//            modeloAnio.addElement(a);
//        }
//        cboAnio.setModel(modeloAnio);
//        cboDia.setModel(modeloDia);
//        cboMateriaPrima.setModel(matera);
//        cboCantidad.setModel(cantidad);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlFormularioMateriaPrima = new javax.swing.JPanel();
        lblMateriaPrima = new javax.swing.JLabel();
        cboMateriaPrima = new javax.swing.JComboBox<String>();
        lblCantidad = new javax.swing.JLabel();
        cboCantidad = new javax.swing.JComboBox<String>();
        lblFechaCaducidad = new javax.swing.JLabel();
        cboDia = new javax.swing.JComboBox<String>();
        cboMes = new javax.swing.JComboBox<String>();
        cboAnio = new javax.swing.JComboBox<String>();
        btnEntrada = new javax.swing.JButton();
        pnlBarra = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnEntrada1 = new javax.swing.JButton();
        btnSalida1 = new javax.swing.JButton();
        btnCerrarS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLogo.setBackground(new java.awt.Color(122, 35, 35));

        jLabel1.setFont(new java.awt.Font("Vladimir Script", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 194, 141));
        jLabel1.setText("Damayte Dulce Gourmet");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 194, 141));
        jLabel3.setText("Entrada de Materia Prima");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logodesktop.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogo, java.awt.BorderLayout.PAGE_START);

        pnlFormularioMateriaPrima.setBackground(new java.awt.Color(213, 194, 141));

        lblMateriaPrima.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblMateriaPrima.setText("Nombre Materia Prima");

        cboMateriaPrima.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        cboMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMateriaPrimaActionPerformed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblCantidad.setText("Cantidad");

        cboCantidad.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N

        lblFechaCaducidad.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        lblFechaCaducidad.setText("Fecha de Caducidad");

        cboDia.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        cboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia" }));

        cboMes.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        cboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cboAnio.setFont(new java.awt.Font("Sitka Text", 0, 10)); // NOI18N
        cboAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año" }));

        btnEntrada.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnEntrada.setText("Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioMateriaPrimaLayout = new javax.swing.GroupLayout(pnlFormularioMateriaPrima);
        pnlFormularioMateriaPrima.setLayout(pnlFormularioMateriaPrimaLayout);
        pnlFormularioMateriaPrimaLayout.setHorizontalGroup(
            pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioMateriaPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaCaducidad)
                    .addComponent(lblCantidad)
                    .addComponent(lblMateriaPrima))
                .addGap(34, 34, 34)
                .addGroup(pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEntrada)
                        .addGroup(pnlFormularioMateriaPrimaLayout.createSequentialGroup()
                            .addComponent(cboDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cboMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        pnlFormularioMateriaPrimaLayout.setVerticalGroup(
            pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioMateriaPrimaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMateriaPrima)
                    .addComponent(cboMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidad)
                    .addComponent(cboCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaCaducidad))
                .addGap(29, 29, 29)
                .addComponent(btnEntrada)
                .addGap(22, 22, 22))
        );

        getContentPane().add(pnlFormularioMateriaPrima, java.awt.BorderLayout.PAGE_END);

        pnlBarra.setBackground(new java.awt.Color(9, 57, 5));
        pnlBarra.setPreferredSize(new java.awt.Dimension(449, 35));

        btnRegistro.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        pnlBarra.add(btnRegistro);

        btnEntrada1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnEntrada1.setText("Entradas");
        btnEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrada1ActionPerformed(evt);
            }
        });
        pnlBarra.add(btnEntrada1);

        btnSalida1.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnSalida1.setText("Salidas");
        btnSalida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalida1ActionPerformed(evt);
            }
        });
        pnlBarra.add(btnSalida1);

        btnCerrarS.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btnCerrarS.setText("Cerrar Sesion");
        btnCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSActionPerformed(evt);
            }
        });
        pnlBarra.add(btnCerrarS);

        getContentPane().add(pnlBarra, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed

        viewRegistroMateriaPrima registro = new viewRegistroMateriaPrima();
        registro.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrada1ActionPerformed
        viewEntradaMateriaPrima entrada = new viewEntradaMateriaPrima();
        entrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrada1ActionPerformed

    private void btnSalida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalida1ActionPerformed
        viewSalidaMateriaPrima salida = new viewSalidaMateriaPrima();
        salida.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalida1ActionPerformed

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
        JOptionPane.showMessageDialog(null, "Hasta Pronto");
        viewLogin login = new viewLogin();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarSActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
             try {
        AccessMySQL objCon = AccessMySQL.getInstance();
        //Paso 1 obtener la conexion
        Connection con=objCon.getConnection();
        String nom,cant;
        nom=cboMateriaPrima.getSelectedItem().toString();
        cant=cboCantidad.getSelectedItem().toString();
        
        Statement stmt= con.createStatement();
        String query= "SELECT cantidad "
                + "FROM materiaprima where nombreMP='"+nom+ "' ";
       
        ResultSet rsut = stmt.executeQuery(query);
        if(rsut.next()){
           
            String update="UPDATE materiaprima SET  cantidad=cantidad +'"+cant+"' WHERE nombreMP='"+nom+"' ";
            stmt.executeUpdate(update);
        }
        if(cboMateriaPrima.getSelectedItem().equals("Nombre")){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la Materia Prima","Mensaje",JOptionPane.ERROR_MESSAGE);
            
        } else if(cboCantidad.getSelectedItem().equals("Cantidad")){
            JOptionPane.showMessageDialog(null, "No se ha seleccionado la cantidad","Mensaje",JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        Logger.getLogger(viewSalidaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
            // TODO add your handling code here:
           
        
        
        
            
            if (cboMateriaPrima.getSelectedItem().equals("Seleccione la Materia prima")) {
                JOptionPane.showMessageDialog(null, "Seleccione la Materia prima",
                        "Mensaje", JOptionPane.ERROR_MESSAGE);
            } else {
                if (cboCantidad.getSelectedItem().equals("Sleccione la cantidad")) {
                    JOptionPane.showMessageDialog(null, "Sleccione la cantidad",
                            "Mensaje", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (cboDia.getSelectedItem().equals("Dia")) {
                        JOptionPane.showMessageDialog(null, "Sleccione el Dia",
                                "Mensaje", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (cboMes.getSelectedItem().equals("Mes")) {
                            JOptionPane.showMessageDialog(null, "Sleccione el Mes",
                                    "Mensaje", JOptionPane.ERROR_MESSAGE);
                        } else {
                            if (cboAnio.getSelectedItem().equals("Año")) {
                                JOptionPane.showMessageDialog(null, "Slecciona el Año",
                                        "Mensaje", JOptionPane.ERROR_MESSAGE);
                            } else {
                                JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                            }
                        }
                    }
                }
            }
       
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void cboMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMateriaPrimaActionPerformed
//        try {
//            // TODO add your handling code here:
//            AccessMySQL objCon = AccessMySQL.getInstance();
//            //Paso 1 obtener la conexion
//            Connection con=objCon.getConnection();
//            //Paso 2 Crear un enunciado
//            Statement stmt= con.createStatement();
//        
//            String query= "SELECT nombreMP "
//                    + "FROM materiaprima ";
//            cboMateriaPrima.removeAllItems();
//            
//            ResultSet rsut = stmt.executeQuery(query);
//            // System.out.println("valores"+rsut);
//            while(rsut.next()){
//                cboMateriaPrima.addItem(rsut.getString(1));
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(viewEntradaMateriaPrima.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_cboMateriaPrimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewEntradaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewEntradaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewEntradaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewEntradaMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewEntradaMateriaPrima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnEntrada1;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalida1;
    private javax.swing.JComboBox<String> cboAnio;
    private javax.swing.JComboBox<String> cboCantidad;
    private javax.swing.JComboBox<String> cboDia;
    private javax.swing.JComboBox<String> cboMateriaPrima;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblFechaCaducidad;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlFormularioMateriaPrima;
    private javax.swing.JPanel pnlLogo;
    // End of variables declaration//GEN-END:variables
}
