
package view;

import dao.PedidoDAO;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Santana Mares Jasmin Aide sant.mar.1997@gmail.com
 */
public class ViewPedidos extends javax.swing.JFrame {

    private PedidoDAO dao = new PedidoDAO();

 
    public ViewPedidos() {

        initComponents();
        setSize(new java.awt.Dimension(500, 400));
        // initCombos();
        List<Usuario> lista = dao.getListaUsuario();
        cboUsuario.removeAllItems();
        for (Usuario usuario : lista) {
            cboUsuario.addItem(usuario.getNombreUsuario() + "" + usuario.getApPat() + " " + usuario.getApMat());
        }
        panCards.add(panListar, "listar");
    }

//    private void initCombos() {
//
//        cboColonia.setModel(new DefaultComboBoxModel<>(new String[]{
//        "Seleccione la Colonia","Dolores Hidalgo","El pipila","San Cristobal", 
//            "Adjuntas del Rio","15 de Septiembre","Lindavista","Arboledas","Fracc. Guanajuato",
//            "Valle verde","San Pablo","San Agustin"
//            }));
//        
//       
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        panBoton = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        panCards = new javax.swing.JPanel();
        panAgregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCalle = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboColonia = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cboUsuario = new javax.swing.JComboBox();
        panListar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panEliminar = new javax.swing.JPanel();
        panModificar = new javax.swing.JPanel();
        panEtatus = new javax.swing.JPanel();
        panOperadores = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Administración de Pedidos");
        getContentPane().add(lblTitulo, java.awt.BorderLayout.PAGE_START);

        lblEstatus.setText("Estatus");
        getContentPane().add(lblEstatus, java.awt.BorderLayout.PAGE_END);

        panBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panBoton.setLayout(new javax.swing.BoxLayout(panBoton, javax.swing.BoxLayout.Y_AXIS));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnAgregarKeyTyped(evt);
            }
        });
        panBoton.add(btnAgregar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panBoton.add(btnEliminar);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panBoton.add(btnModificar);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        panBoton.add(btnListar);

        getContentPane().add(panBoton, java.awt.BorderLayout.LINE_END);

        panCards.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panCards.setLayout(new java.awt.CardLayout());

        panAgregar.setLayout(new java.awt.GridLayout(6, 2));

        jLabel3.setText("Clave");
        panAgregar.add(jLabel3);

        txtClave.setEditable(false);
        panAgregar.add(txtClave);

        jLabel4.setText("Fecha");
        panAgregar.add(jLabel4);

        txtFecha.setEditable(false);
        panAgregar.add(txtFecha);

        jLabel5.setText("Calle");
        panAgregar.add(jLabel5);

        txtCalle.setColumns(20);
        txtCalle.setRows(5);
        jScrollPane1.setViewportView(txtCalle);

        panAgregar.add(jScrollPane1);

        jLabel6.setText("Número");
        panAgregar.add(jLabel6);
        panAgregar.add(txtNumero);

        jLabel7.setText("Colonia");
        panAgregar.add(jLabel7);

        panAgregar.add(cboColonia);

        jLabel8.setText("Usuario");
        panAgregar.add(jLabel8);

        panAgregar.add(cboUsuario);

        panCards.add(panAgregar, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout panListarLayout = new javax.swing.GroupLayout(panListar);
        panListar.setLayout(panListarLayout);
        panListarLayout.setHorizontalGroup(
            panListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panListarLayout.setVerticalGroup(
            panListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panCards.add(panListar, "card5");

        javax.swing.GroupLayout panEliminarLayout = new javax.swing.GroupLayout(panEliminar);
        panEliminar.setLayout(panEliminarLayout);
        panEliminarLayout.setHorizontalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panEliminarLayout.setVerticalGroup(
            panEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panCards.add(panEliminar, "card4");

        javax.swing.GroupLayout panModificarLayout = new javax.swing.GroupLayout(panModificar);
        panModificar.setLayout(panModificarLayout);
        panModificarLayout.setHorizontalGroup(
            panModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panModificarLayout.setVerticalGroup(
            panModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panCards.add(panModificar, "card5");

        getContentPane().add(panCards, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panEtatusLayout = new javax.swing.GroupLayout(panEtatus);
        panEtatus.setLayout(panEtatusLayout);
        panEtatusLayout.setHorizontalGroup(
            panEtatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panEtatusLayout.setVerticalGroup(
            panEtatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        getContentPane().add(panEtatus, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout panOperadoresLayout = new javax.swing.GroupLayout(panOperadores);
        panOperadores.setLayout(panOperadoresLayout);
        panOperadoresLayout.setHorizontalGroup(
            panOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        panOperadoresLayout.setVerticalGroup(
            panOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        getContentPane().add(panOperadores, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyTyped
        // TODO add your handling code here:
        if (txtCalle.equals("")) {
            JOptionPane.showMessageDialog(this, "El campo calle esta vacio");
        }

    }//GEN-LAST:event_btnAgregarKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panCards.getLayout();
        layout.show(panCards, "card2");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panCards.getLayout();
        layout.show(panCards, "card4");
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panCards.getLayout();
        layout.show(panCards, "card3");
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) panCards.getLayout();
        layout.show(panCards, "listar");
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cboColonia;
    private javax.swing.JComboBox cboUsuario;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panAgregar;
    private javax.swing.JPanel panBoton;
    private javax.swing.JPanel panCards;
    private javax.swing.JPanel panEliminar;
    private javax.swing.JPanel panEtatus;
    private javax.swing.JPanel panListar;
    private javax.swing.JPanel panModificar;
    private javax.swing.JPanel panOperadores;
    private javax.swing.JTextArea txtCalle;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
